### ISSUE TITLE
app操作有发生报错，却没收集到错误日志

### ISSUE THREAD

**Issue by zoujinbin** [TinkerXXX/umeng_uapp#2]
可以明确app操作是有错误发生的，正常情况下会有相应的错误日志，但是为什么友盟统计面板上看不到错误信息呢，错误趋势和错误列表统计指标都是0。我查了下文档：https://developer.umeng.com/docs/66632/detail/66889#h2-u9519u8BEFu7EDFu8BA111，错误统计默认是打开的。麻烦您看看为什么没有收集到app端的错误日志

**Comment by TinkerXXX** [comment]
请确认是否是umeng SDK的错误，插件本身并没有调用setCatchUncaughtExceptions，也没有try-catch umeng SDK相关代码
